### PR TITLE
added javascript linter

### PR DESCRIPTION
**Pull request by Ifeanyi30**
This pull request solves the issue #1

### CODE REVIEW

**Comment by lacabra** [comment]
Thanks @Ifeanyi30 for your work on this Pull Request. Much appreciated. Before we can merge it, can you please look at the [failed build](https://github.com/unicef/kindly-website/runs/4069402391?check_suite_focus=true), and correct the errors ? Thank you!

**Comment by Ifeanyi30** [comment]
Hi @lacabra, I have edited the PR, please review and merge thanks. Also is there any format for creating a pull request or do I just march-up my intent.

**Comment by lacabra** [comment]
@Ifeanyi30 the build continues to fail, we can't merge this PR until the build succeeds. Look at the logs by clicking the red cross ❌ next to the last commit, and address the errors that are displayed there.

I acknowledge that those errors are not introduced by any code that you have authored and most are stylistic changes that you should be able to fix. Let me know if you have any questions.

We don't have a template for PRs, you can describe what your proposed changes do, or refer to existing PR templates from other repos.

Thank you!

**Comment by Ifeanyi30** [comment]
Thanks, @lacabra for the feedback. I have added a few rules to the linter config file and hopefully, it would build successfully this time.

**Comment by lacabra** [comment]
@Ifeanyi30 Thanks for your contribution, but it's not in the right direction. Please revert commit d8aa245. You should not modify the linter config at this point as it is properly configured. 

The way of fixing the errors is to go to the code and make the necessary changes so that the linter passes, without changing the existing rules, which are properly configured.

Please make sure that the linter passes locally before pushing to this repo to streamline this pull request. Locally run `npm run lint:fix` which should automatically fix most errors, and fix the rest manually. Do not commit until `npm run lint` runs successfully.

Thanks

**Comment by Ifeanyi30** [comment]
@lacabra I had to edit the package.json file because of the prettier error I was having and to let the Eslint config gain more control of the prettier rules configured. I also added the prettier-ignore comment to the 404 and index.html public file since prettier automatically sets chained methods to be on each line (this gives an error).

**Comment by Ifeanyi30** [comment]
Hi @lacabra, pls review the changes

**Comment by lacabra** [comment]
@Ifeanyi30 Thanks for your contribution towards this PR. Unfortunately, the build still fails. See the status check next to your last commit, and there are many many errors that you should be correcting. It strikes me that in your last commit, you only fix one of those many errors. Let me know if you need additional guidance beyond what I have explained in my previous comments.

**Comment by Ifeanyi30** [comment]
I didn't get any errors in my local repo when I run <code>yarn run lint</code> and <code>yarn run lint:fix</code>

**Comment by lacabra** [comment]
@Ifeanyi30 If you look into the failed build, the command that errors out is `yarn run build`. Try running this locally.

**Comment by Ifeanyi30** [comment]
@lacabra, I did not get any error when I ran the <code>yarn build</code> command but I have also added two prettier rules:
<pre>
{
  "endOfLine": "auto",
  "useTabs": false
}
</pre>

What do you think?

**Comment by Ifeanyi30** [comment]
This is the result of the build command:
build

**Comment by lacabra** [comment]
Thanks @Ifeanyi30 for the back and forth and for your contribution. When I run the `yarn build` locally I get an error on a function being duplicated introduced in one of the commits, and when I fix that I get the same errors as the CI is reporting. I will proceed to merge this PR, and make adjustments in a subsequent PR. Thanks again.

**Review by lacabra — APPROVED** [review]

**Comment by Ifeanyi30** [comment]
Thanks @lacabra, I would also like to see the PR you want to use to correct the build error to know where I went wrong.

**Comment by lacabra** [comment]
@Ifeanyi30 I wouldn't say you were wrong. Sometimes git gets things mixed up with multiple merges. I am surprised that you didn't see the errors in your local environment and that both the CI and I did, but at some point it's not worth trying to troubleshoot this any longer, instead we merge, and start anew with another PR (see #7) and fix any issues that arise there. I made some changes to the config, but were all very minor. Thanks again.

**Pull request merged**
