### PR TITLE
updated yes and no values in feedback response

### PR DESCRIPTION
**Pull request by nathanfletcher**
This commit fixes the data mismatch in issue #38

### CODE REVIEW

**Comment by sabinevidal** [comment]
@nathanfletcher  : So I think this was on purpose, as the Google Sheet only looks at whether bullying is detected with 'yes' or 'no', they're swapped here to make this work in the sheets. So for the situations where cyberbullying is not detected, the question asks whether the user agrees yes/ no. User answers 'Yes' there's no cyberbullying, which translates into `no` bullying was not detected and vice versa.
@lacabra can confirm?

**Comment by lacabra** [comment]
@nathanfletcher: @sabinevidal  is correct (we went through this once before, if I recall correctly), I advise not to change these values, and I ask not to merge this PR. 

Ultimately, what gets submitted to the data is whether a sentence contains cyberbullying intent or not, by combining what the ML algo detects and whether the user validates it or not. The actual response from the user is not the definitive one, it depends on whether the ML algo was right or not.

So the decision tree is as follows:

- cyberbullying intent detected -> user agrees -> tag "YES"
- cyberbullying intent detected -> user disagrees -> tag "NO"
- cyberbullying intent not detected -> user agrees -> tag "NO"
- cyberbullying intent not detected  -> user disagrees -> tag "YES"

**Comment by nathanfletcher** [comment]
@lacabra okay got it.
@sabinevidal is there a way we can explain this in the Google Sheet workflow because it seems to me it should be defined or explained somewhere (maybe in the docs?).

**Comment by sabinevidal** [comment]
@nathanfletcher yeah, will add a comment to the code and then include it in the docs too.

**Comment by sabinevidal** [comment]
Adding comment in docs in https://github.com/unicef/kindly/pull/115 to make this choice clear

**Pull request closed without merging**
